export const ADD_LAPTOP_PENDING = "ADD_LAPTOP_PENDING";
export const ADD_LAPTOP_FULFILLED = "ADD_LAPTOP_FULFILLED";
export const ADD_LAPTOP_REJECTED = "ADD_LAPTOP_REJECTED";
export const FETCH_LAPTOPS_PENDING = "FETCH_LAPTOPS_PENDING";
export const FETCH_LAPTOPS_FULFILLED = "FETCH_LAPTOPS_FULFILLED";
export const FETCH_LAPTOPS_REJECTED = "FETCH_LAPTOPS_REJECTED";
export const UPDATE_LAPTOP_PENDING = "UPDATE_LAPTOP_PENDING";
export const UPDATE_LAPTOP_FULFILLED = "UPDATE_LAPTOP_FULFILLED";
export const UPDATE_LAPTOP_REJECTED = "UPDATE_LAPTOP_REJECTED";
export const DELETE_LAPTOP_PENDING = "DELETE_LAPTOP_PENDING";
export const DELETE_LAPTOP_FULFILLED = "DELETE_LAPTOP_FULFILLED";
export const DELETE_LAPTOP_REJECTED = "DELETE_LAPTOP_REJECTED";

